services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
