services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"
    
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  db:
    image: postgres:17-alpine
    container_name: postgres
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "220MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
