services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app
    networks:
      - backend

  db:
    image: postgres:17-alpine
    container_name: postgres
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
